{{- range .Values.streams }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stream-{{ .stream }}
  namespace: {{ $.Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stream-{{ .stream }}
  template:
    metadata:
      labels:
        teknoir.org/app: stream-{{ .stream }}
        app: stream-{{ .stream }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap_env.yaml") $ | sha256sum }}
    spec:
      serviceAccountName: "{{ default $.Values.defaults.serviceAccountName .serviceAccountName }}"
      containers:
        - name: {{ .stream }}
          image: "{{ default $.Values.defaults.image.repository (default (dict "repository" $.Values.defaults.image.repository) .image).repository }}:{{ default $.Values.defaults.image.tag (default (dict "tag" $.Values.defaults.image.tag) .image).tag }}"
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: stream-{{ .stream }}-env-config
          env:
            - name: MQTT_CREDENTIALS
              valueFrom:
                secretKeyRef:
                  name: mqtt-bootstrap-user
                  key: bootstrap_user
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: {{ default $.Values.defaults.mongodbSecretKeyRef.name (default (dict "name" $.Values.defaults.mongodbSecretKeyRef.name) .mongodbSecretKeyRef).name }}
                  key: {{ default $.Values.defaults.mongodbSecretKeyRef.key (default (dict "key" $.Values.defaults.mongodbSecretKeyRef.key) .mongodbSecretKeyRef).key }}
            - name: REID_MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: {{ default $.Values.defaults.reIdMongodbSecretKeyRef.name (default (dict "name" $.Values.defaults.reIdMongodbSecretKeyRef.name) .reIdMongodbSecretKeyRef).name }}
                  key: {{ default $.Values.defaults.reIdMongodbSecretKeyRef.key (default (dict "key" $.Values.defaults.reIdMongodbSecretKeyRef.key) .reIdMongodbSecretKeyRef).key }}
          resources:
            {{- toYaml (default $.Values.defaults.resources .resources) | nindent 12 }}
{{- end }}